### ISSUE TITLE
Headless Warning, Please help!!!!!!!!!!

### ISSUE THREAD

**Issue by Msoffice12314** [daydos/us-visa-appointment#9]
![headless error](https://github.com/daydos/us-visa-appointment/assets/137712013/7d02518b-0865-48cd-9f7b-5e2374ab0f03)

Please help me fix this !!!

**Comment by KaranmaanCanada** [comment]
> ![headless error](https://user-images.githubusercontent.com/137712013/248569058-7d02518b-0865-48cd-9f7b-5e2374ab0f03.png)
> 
> Please help me fix this !!!

How did you fix this bro

**Comment by Danilo-GB** [comment]
If I'm not wrong, just change:
const browser = await puppeteer.launch();

to:
const browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox']
      })

**Comment by KaranmaanCanada** [comment]
> If I'm not wrong, just change: const browser = await puppeteer.launch();
> 
> to: const browser = await puppeteer.launch({ headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox'] })

Still getting the same error, please help

**Comment by Danilo-GB** [comment]
Can you paste your full output pls?

**Comment by KaranmaanCanada** [comment]
> Can you paste your full output pls?

It’s the same as mentioned on the top . Same output as [he’s](https://github.com/daydos/us-visa-appointment/issues/9#issue-1773351772) getting

**Comment by Danilo-GB** [comment]
I mean... you could try with 
const browser = await puppeteer.launch({
    headless: 'new'
  });
  
as the warning says, however, it is a warning, it should not stop the project, are you sure you don't have any other issue?
did you added the extra headers as the [pr](https://github.com/daydos/us-visa-appointment/pull/10)?

**Comment by KaranmaanCanada** [comment]
> I mean... you could try with const browser = await puppeteer.launch({ headless: 'new' });
> 
> as the warning says, however, it is a warning, it should not stop the project, are you sure you don't have any other issue? did you added the extra headers as the [pr](https://github.com/daydos/us-visa-appointment/pull/10)?

Actually I’m not friendly with 

> I mean... you could try with const browser = await puppeteer.launch({ headless: 'new' });
> 
> as the warning says, however, it is a warning, it should not stop the project, are you sure you don't have any other issue? did you added the extra headers as the [pr](https://github.com/daydos/us-visa-appointment/pull/10)?

Actually I’m not friendly with The puppeteer. I’m able to run https://github.com/Soroosh-N/us_visa_scheduler , this python project easily bubuy not the java one . When i’m putting arguments in terminal it’s just showing this https://github.com/daydos/us-visa-appointment/issues/9#issue-1773351772
